@baseUrl  = localhost
@integrationName = test

###

# @name login
POST http://{{baseUrl}}/auth/login
Workspaces-Identifier: jnkconsult
Content-Type: application/json
Accept: application/json
Accept-Encoding: gzip
X-Integration-Name: {{integrationName}}

{
    "email" : "jms@grazulex.be",
    "password" : "password"
}

###

@token = {{login.response.body.$.token}}

GET http://{{baseUrl}}/users
Workspaces-Identifier: jnkconsult
Content-Type: application/json
Accept: application/json
Accept-Encoding: gzip
X-Integration-Name: {{integrationName}}
Authorization: Bearer {{token}}

###

@token = {{login.response.body.$.token}}

GET http://{{baseUrl}}/projects
Workspaces-Identifier: jnkconsult
Content-Type: application/json
Accept: application/json
Accept-Encoding: gzip
X-Integration-Name: {{integrationName}}
Authorization: Bearer {{token}}